hw05_final/yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

hw05_final/yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('not_follow/', views.not_follow, name='not_follow'),
]

hw05_final/yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

hw05_final/yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             related_name='comments',
                             on_delete=models.CASCADE,
                             )
    author = models.ForeignKey(User,
                               related_name='comments',
                               on_delete=models.CASCADE,
                               )
    text = models.TextField('Текст комментария',
                            help_text='Введите текст комментария'
                            )
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

    class Meta:
        constraints = [models.UniqueConstraint(fields=['author', 'user'],
                                               name='unique_follower')
                       ]

    class Meta:
        constraints = [models.UniqueConstraint(fields=['author', 'user'],
                                               name='unique_follower')
                       ]

hw05_final/yatube/posts/forms.py
from typing import Type

from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model: Type[Post] = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

hw05_final/yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow

NMB_PUB = 10


def paginator(request, posts):
    page_number = request.GET.get('page')
    page_obj = Paginator(posts, NMB_PUB).get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.order_by('-pub_date')
    page_obj = paginator(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    page_obj = paginator(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = False
    if (request.user.is_authenticated and Follow.objects.filter(
            author=author.id, user=request.user.id).exists()):
        following = True
    posts = author.posts.all().order_by('-pub_date')
    post_count = posts.count()
    page_obj = paginator(request, posts)
    context = {
        'author': author,
        'page_obj': page_obj,
        'post_count': post_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    author_posts = author.posts
    post_count = author_posts.count()
    comments = Comment.objects.filter(post=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'title': post.text,
        'post': post,
        'post_count': post_count,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=post.author)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,

    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user).order_by('-pub_date')
    paginator = Paginator(posts, NMB_PUB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "posts/follow.html",
                  {"page_obj": page_obj})

def not_follow(request):
    return render(request, 'posts/not_follow.html')

@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
        return redirect('posts:follow_index')
    else:
        return redirect('posts:not_follow')


@login_required
def profile_unfollow(request, username):
    follow_user = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=follow_user).delete()
    return redirect('posts:follow_index')

hw05_final/yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class='container py-5'>
    <div class='row justify-content-center'>
      <div class='col-md-8 p-5'>
        <div class='card'>
          <div class='card-header'>
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class='card-body'>
            {% load user_filters %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">

            {% if is_edit %}
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <form method='post' action="{% url 'posts:post_edit' post.pk %}">
              {% csrf_token %}
            {% else %}
              <form method='post' action="{% url 'posts:post_create' %}">
              {% csrf_token %}
            {% endif %}




            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">
                    *
                  </span>
                {% endif %}
              </label>
              {{field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          {% endfor %}

            <div class='d-flex justify-content-end'>
              <button type='submit' class='btn btn-primary'>
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

hw05_final/yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  Подписки на авторов
{% endblock %}
{% cache 20 sidebar %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">
    <h1>Последние обновления у избранных авторов</h1>
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
            </a>
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </article>
      <article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}{% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </article>
  </div>
{% endblock %}
{% endcache %}

hw05_final/yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>
      {{ group.description }}
  </p>
  <article>
      {% for post in page_obj %}
        <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaks }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </article>
</div>
{% endblock %}

hw05_final/yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последнее обновления на сайте
{% endblock %}
{% block content %}
  {% load cache %}
  {% cache 20 sidebar %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
            </a>
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </article>
      <article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}{% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
      </article>
  </div>
{% endblock %}

hw05_final/yatube/templates/posts/not_follow.html
{% extends 'base.html' %}
{% block title %}
  Подписки на авторов
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h4>Вы не можете подписаться на самого себя!</h4>
    <a href="{% url 'posts:index' %}">
      На главную
    </a>
    <br>
  </div>
{% endblock %}

hw05_final/yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post.text|slice:':30' }}{% endblock %}
{% block content %}
  <div class="container py-5">
  <div class='row'>
    <aside class='col-12 col-md-3'>
      <ul class='list-group list-group-flush'>
        <li class='list-group-item'>
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% if post.group %}
          <li class='list-group-item'>
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Bсе записи группы
            </a>
          </li>
          <li class='list-group-item'>
            Автор: {{ post.author.username }}
          </li>
          <li class='list-group-item d-flex justify-content-between align-items-center'>
            Всего постов автора: <span>{{ post.author.posts.count }}</span>
          </li>
        {% endif %}
        <li class='list-group-item'>
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class='col-12 col-md-9'>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}
      {% if request.user == post.author %}
        <a class='btn btn-primary' href="{% url 'posts:post_edit' post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
    </article>
  </div>
  </div>
{% endblock %}

hw05_final/yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{author.get_full_name }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} {{ posts }}</h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  </div>
    <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>
      {{ post.text|linebreaksbr}}
    </p>
      {% if post.author %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      {% endif %}
    </article>
      <p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

hw05_final/yatube/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class='container py-5'>
    <div class='row justify-content-center'>
      <div class='col-md-8 p-5'>
        <div class='card'>
          <div class='card-header'>
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class='card-body'>
            {% if is_edit %}
              <form method='post' action="{% url 'posts:post_edit' post.pk %}">
              {% csrf_token %}
            {% else %}
              <form method='post' action="{% url 'posts:post_create' %}">
              {% csrf_token %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class='form-group row my-3 p-3'>
              <label for='id_text'>
                Текст поста
                <span class='required text-danger'>*</span>
              </label>
              <textarea name='text' cols='40' rows='10' class='form-control' required id='id_text'>
                {{ post.text }}
              </textarea>
              <small id='id_text-help' class='form-text text-muted'>
                Текст нового поста
              </small>
            </div>
            <div class='form-group row my-3 p-3'>
              <label for='id_group'>
                Group
              </label>
              <select name='group' class='form-control' id='id_group'>
                {% for group in form.group %}
                  <option value='{{ group }}'>{{ group }}</option>
                {% endfor %}
              </select>
              <small id='id_group-help' class='form-text text-muted'>
                Группа, к которой будет относиться пост
              </small>
            </div>
            <div class='d-flex justify-content-end'>
              <button type='submit' class='btn btn-primary'>
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}